apiVersion: v1
kind: Service
metadata:
  name: todo
  labels:
    service: todo
    tier: backend
    transport: grpc
spec:
  ports:
  - port: 8080
  selector:
    service: todo
    tier: backend
    transport: grpc
