apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: proxy
        tier: infra
    spec:
      containers:
      - name: proxysrv
        image: vems/proxy:v1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
