apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    service: proxy
    tier: infra
spec:
  # if using minikube, uncomment the following to automatically expose as public
  # port to access this service externally
  type: NodePort

  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
    # if using NodePort, uncomment the following to expose a public port value
    nodePort: 30080
  selector:
    service: proxy
    tier: infra
